package com.adserversoft.flexfuse.client.model.vo {
import com.adserversoft.flexfuse.client.ApplicationFacade;
import com.adserversoft.flexfuse.client.model.ApplicationConstants;
import com.adserversoft.flexfuse.client.model.BannerProxy;

//[Bindable]
//[RemoteClass(alias="com.adserversoft.flexfuse.server.api.Banner")]
public dynamic class BannerFileVO extends BaseVO {
    public var uid:String;// uid for file generated by client
    public var parentUid:String; // uid parent banner

    public var bannerContentTypeId:int;
    public var adFormatId:int;
    public var filename:String;
    public var fileSize:int;

    public function BannerFileVO(adFormatId:int = 0, filename:String = null, fileSize:int = 0) {
        this.adFormatId = adFormatId;
        this.filename = filename;
        this.fileSize = fileSize;
    }

    public function get fileSizeString():String {
        var stringFileSize:String = "" + Math.round(fileSize / 1024 * 100) / 100;
        if (stringFileSize.indexOf(".") == -1) {
            stringFileSize += ".00";
        } else if (stringFileSize.substring(stringFileSize.indexOf(".") + 1).length == 1) {
            stringFileSize += "0";
        }
        return stringFileSize.replace(".", ",") + " Kb";
    }

    public function set fileSizeString(s:String):void {
        trace(s);
    }
}
}